<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Controle Biológico de Nematóides - Projeto Final</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./favicon.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Controle Biológico de Nematóides</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target=""><i class="bi bi-house" role="img">
</i> 
 <span class="menu-text">Projeto Final</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Introdução.html" rel="" target=""><i class="bi bi-clipboard" role="img">
</i> 
 <span class="menu-text">Sobre o projeto</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Projeto.html" rel="" target="" aria-current="page"><i class="bi bi-bar-chart" role="img">
</i> 
 <span class="menu-text">Análise de Dados</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/carlosutiamada" rel="" target="">
 <span class="dropdown-text">Carlos Utiamada</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/fecorbelli" rel="" target="">
 <span class="dropdown-text">Fernanda Corbelli</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#pré-análise" id="toc-pré-análise" class="nav-link active" data-scroll-target="#pré-análise">Pré-análise</a>
  <ul class="collapse">
  <li><a href="#pacotes-utilizados" id="toc-pacotes-utilizados" class="nav-link" data-scroll-target="#pacotes-utilizados">Pacotes utilizados</a></li>
  </ul></li>
  <li><a href="#importação-do-conjunto-de-dados" id="toc-importação-do-conjunto-de-dados" class="nav-link" data-scroll-target="#importação-do-conjunto-de-dados">Importação do conjunto de dados</a></li>
  <li><a href="#análise-exploratória-dos-dados" id="toc-análise-exploratória-dos-dados" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados">Análise exploratória dos dados</a>
  <ul class="collapse">
  <li><a href="#gráfico-da-massa-da-parte-aérea-seca-mpas" id="toc-gráfico-da-massa-da-parte-aérea-seca-mpas" class="nav-link" data-scroll-target="#gráfico-da-massa-da-parte-aérea-seca-mpas">Gráfico da massa da parte aérea seca (MPAS)</a></li>
  <li><a href="#gráfico-da-massa-da-raiz-fresca-mrf" id="toc-gráfico-da-massa-da-raiz-fresca-mrf" class="nav-link" data-scroll-target="#gráfico-da-massa-da-raiz-fresca-mrf">Gráfico da massa da raiz fresca (MRF)</a></li>
  <li><a href="#gráfico-do-número-de-ovos-por-planta-ovos" id="toc-gráfico-do-número-de-ovos-por-planta-ovos" class="nav-link" data-scroll-target="#gráfico-do-número-de-ovos-por-planta-ovos">Gráfico do número de ovos por planta (ovos)</a></li>
  <li><a href="#gráfico-do-número-de-ovos-por-grama-de-raiz-fresca-ovosg" id="toc-gráfico-do-número-de-ovos-por-grama-de-raiz-fresca-ovosg" class="nav-link" data-scroll-target="#gráfico-do-número-de-ovos-por-grama-de-raiz-fresca-ovosg">Gráfico do número de ovos por grama de raiz fresca (ovosg)</a></li>
  </ul></li>
  <li><a href="#análise-estatística-e-teste-de-hipóteses" id="toc-análise-estatística-e-teste-de-hipóteses" class="nav-link" data-scroll-target="#análise-estatística-e-teste-de-hipóteses">Análise estatística e teste de hipóteses</a>
  <ul class="collapse">
  <li><a href="#variável-massa-da-parte-aérea-seca-mpas" id="toc-variável-massa-da-parte-aérea-seca-mpas" class="nav-link" data-scroll-target="#variável-massa-da-parte-aérea-seca-mpas">Variável massa da parte aérea seca (MPAS)</a>
  <ul class="collapse">
  <li><a href="#análise-de-variância-anova" id="toc-análise-de-variância-anova" class="nav-link" data-scroll-target="#análise-de-variância-anova">Análise de variância (ANOVA)</a></li>
  </ul></li>
  <li><a href="#variável-massa-da-raiz-fresca-mrf" id="toc-variável-massa-da-raiz-fresca-mrf" class="nav-link" data-scroll-target="#variável-massa-da-raiz-fresca-mrf">Variável massa da raiz fresca (MRF)</a>
  <ul class="collapse">
  <li><a href="#análise-de-variância-anova-1" id="toc-análise-de-variância-anova-1" class="nav-link" data-scroll-target="#análise-de-variância-anova-1">Análise de variância (ANOVA)</a></li>
  <li><a href="#anova-em-relação-aos-tratamentos" id="toc-anova-em-relação-aos-tratamentos" class="nav-link" data-scroll-target="#anova-em-relação-aos-tratamentos">ANOVA em relação aos tratamentos</a></li>
  <li><a href="#anova-em-relação-as-doses" id="toc-anova-em-relação-as-doses" class="nav-link" data-scroll-target="#anova-em-relação-as-doses">ANOVA em relação as doses</a></li>
  <li><a href="#checagem-das-premissas-2" id="toc-checagem-das-premissas-2" class="nav-link" data-scroll-target="#checagem-das-premissas-2">Checagem das premissas</a></li>
  </ul></li>
  <li><a href="#variável-número-de-ovos-por-planta" id="toc-variável-número-de-ovos-por-planta" class="nav-link" data-scroll-target="#variável-número-de-ovos-por-planta">Variável número de ovos por planta</a>
  <ul class="collapse">
  <li><a href="#análise-de-variância-anova-2" id="toc-análise-de-variância-anova-2" class="nav-link" data-scroll-target="#análise-de-variância-anova-2">Análise de variância (ANOVA)</a></li>
  </ul></li>
  <li><a href="#variável-número-de-ovos-por-grama-de-raiz-fresca" id="toc-variável-número-de-ovos-por-grama-de-raiz-fresca" class="nav-link" data-scroll-target="#variável-número-de-ovos-por-grama-de-raiz-fresca">Variável número de ovos por grama de raiz fresca</a>
  <ul class="collapse">
  <li><a href="#análise-de-variância-anova-3" id="toc-análise-de-variância-anova-3" class="nav-link" data-scroll-target="#análise-de-variância-anova-3">Análise de variância (ANOVA)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#regressão" id="toc-regressão" class="nav-link" data-scroll-target="#regressão">Regressão</a></li>
  <li><a href="#análise-de-correlação" id="toc-análise-de-correlação" class="nav-link" data-scroll-target="#análise-de-correlação">Análise de Correlação</a>
  <ul class="collapse">
  <li><a href="#correlação-entre-ovos-e-massa-de-parte-aérea-seca-mpas" id="toc-correlação-entre-ovos-e-massa-de-parte-aérea-seca-mpas" class="nav-link" data-scroll-target="#correlação-entre-ovos-e-massa-de-parte-aérea-seca-mpas">Correlação entre Ovos e Massa de Parte Aérea Seca (MPAS)</a></li>
  <li><a href="#correlação-entre-ovos-e-massa-de-raiz-fresca-mrf" id="toc-correlação-entre-ovos-e-massa-de-raiz-fresca-mrf" class="nav-link" data-scroll-target="#correlação-entre-ovos-e-massa-de-raiz-fresca-mrf">Correlação entre Ovos e Massa de Raiz Fresca (MRF)</a></li>
  <li><a href="#correlação-entre-massa-de-parte-aérea-seca-mpas-e-massa-de-raiz-fresca-mrf" id="toc-correlação-entre-massa-de-parte-aérea-seca-mpas-e-massa-de-raiz-fresca-mrf" class="nav-link" data-scroll-target="#correlação-entre-massa-de-parte-aérea-seca-mpas-e-massa-de-raiz-fresca-mrf">Correlação entre Massa de Parte Aérea Seca (MPAS) e Massa de Raiz Fresca (MRF)</a></li>
  <li><a href="#correlação-entre-todas-as-variáveis" id="toc-correlação-entre-todas-as-variáveis" class="nav-link" data-scroll-target="#correlação-entre-todas-as-variáveis">Correlação entre todas as variáveis</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Projeto Final</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="pré-análise" class="level1">
<h1>Pré-análise</h1>
<section id="pacotes-utilizados" class="level2">
<h2 class="anchored" data-anchor-id="pacotes-utilizados">Pacotes utilizados</h2>
<p>Todos os pacotes utilizados durante o processo de análise foram carregados previamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcompView)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AgroR)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(drc)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="importação-do-conjunto-de-dados" class="level1">
<h1>Importação do conjunto de dados</h1>
<p>O primeiro passo para qualquer análise de dados é a importação dos dados que serão trabalhados. O conjunto de dados do experimento foi importado de um arquivo Excel (.xlsx) através da função <code>read_excel()</code> do pacote <code>readxl</code>. O nome atribuído ao data frame foi <code>controle</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>controle <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Controle biológico.xlsx"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>controle</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 7
   Trat   Dose   Rep  MPAS   MRF   ovos ovosg
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 A         0     1  22.4  69   121250 1757.
 2 A         0     2  10.9  49.2  49000  996.
 3 A         0     3   3.8  18.8  26000 1383.
 4 A         0     4  11.9  57.3  99000 1728.
 5 A         0     5  21.6  65.1  96000 1475.
 6 A      1000     1  27    68.4 143000 2091.
 7 A      1000     2   9.4  50.4  63000 1250 
 8 A      1000     3  21.8  46.7  35000  749.
 9 A      1000     4   5.2  19.7  17500  888.
10 A      1000     5  15.5  64.5  50000  775.
# ℹ 70 more rows</code></pre>
</div>
</div>
</section>
<section id="análise-exploratória-dos-dados" class="level1">
<h1>Análise exploratória dos dados</h1>
<p>Para uma análise visual do conjunto de dados foi utilizado a função <code>ggplot()</code> do pacote <code>tidyverse</code> e diferentes formatos gráficos. Cada variável resposta foi visualizada de forma individual.</p>
<p><strong>Gráfico de pontos</strong>: O gráfico de pontos possibilita a visualização dos dados coletados de forma individualizada. Esse tipo de gráfico é recomendado quando cada tratamento apresenta poucas repetições, para que não seja um gráfico poluído. Como o conjunto de dados em questão apresenta somente 5 repetições, o gráfico de pontos pode ser utilizado. Para construir esse gráfico foi utilizado o <code>geom_jitter()</code>.</p>
<p><strong>Gráfico de barra do erro</strong>: O gráfico de barra do erro possibilita visualizar a variabilidade dos dados em cada grupo, podendo ser utilizado como referência o desvio padrão ou o erro padrão. Nesse caso, utilizamos o desvio padrão que descreve o quão próximos os valores observados estão da média. A função <code>stat_summary()</code> com o argumento <code>fun.data = "mean_sdl"</code> foram utilizados para gerar a barra do erro e a média dos dados.</p>
<p>Para melhor visualização das variáveis respostas, utilizamos a “Dose” como um fator e adicionamos facetas com a função <code>facet_wrap()</code> para vizualizarmos os tratamentos separadamente.</p>
<section id="gráfico-da-massa-da-parte-aérea-seca-mpas" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-da-massa-da-parte-aérea-seca-mpas">Gráfico da massa da parte aérea seca (MPAS)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">factor</span>(Dose), MPAS, <span class="at">color =</span> <span class="fu">factor</span>(Dose)))<span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">"gray70"</span>)<span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trat)<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_sdl"</span>, <span class="at">fun.args =</span> <span class="fu">list</span>(<span class="at">mult =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="gráfico-da-massa-da-raiz-fresca-mrf" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-da-massa-da-raiz-fresca-mrf">Gráfico da massa da raiz fresca (MRF)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">factor</span>(Dose), MRF, <span class="at">color =</span> <span class="fu">factor</span>(Dose)))<span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">"gray70"</span>)<span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trat)<span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_sdl"</span>, <span class="at">fun.args =</span> <span class="fu">list</span>(<span class="at">mult =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="gráfico-do-número-de-ovos-por-planta-ovos" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-do-número-de-ovos-por-planta-ovos">Gráfico do número de ovos por planta (ovos)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">factor</span>(Dose), ovos, <span class="at">color =</span> <span class="fu">factor</span>(Dose)))<span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">"gray70"</span>)<span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trat)<span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_sdl"</span>, <span class="at">fun.args =</span> <span class="fu">list</span>(<span class="at">mult =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="gráfico-do-número-de-ovos-por-grama-de-raiz-fresca-ovosg" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-do-número-de-ovos-por-grama-de-raiz-fresca-ovosg">Gráfico do número de ovos por grama de raiz fresca (ovosg)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">factor</span>(Dose), ovosg, <span class="at">color =</span> <span class="fu">factor</span>(Dose)))<span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>, <span class="at">color =</span> <span class="st">"gray70"</span>)<span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Trat)<span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_sdl"</span>, <span class="at">fun.args =</span> <span class="fu">list</span>(<span class="at">mult =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="análise-estatística-e-teste-de-hipóteses" class="level1">
<h1>Análise estatística e teste de hipóteses</h1>
<p>O conjunto de dados do experimento apresenta dois fatores: Tratamento e Dose. Desse modo, é preciso realizar a análise de variância de dois fatores (Two-Way ANOVA) para cada uma das quatro variáveis respostas. As hipóteses a serem testadas para cada uma das variáveis resposta são três hipóteses nulas e três hipóteses alternativas.</p>
<section id="variável-massa-da-parte-aérea-seca-mpas" class="level2">
<h2 class="anchored" data-anchor-id="variável-massa-da-parte-aérea-seca-mpas">Variável massa da parte aérea seca (MPAS)</h2>
<ul>
<li><strong>Hipótese nula 1 (H01)</strong>: não há diferença na média da massa da parte aérea seca entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese alternativa 1 (Ha1)</strong>: há pelo menos uma diferença na média da massa da parte aérea seca entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese nula 2 (H02)</strong>: não há diferença na média da massa da parte aérea seca entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese alternativa 2 (Ha2)</strong>: há pelo menos uma diferença na média da massa da parte aérea seca entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese nula 3 (H03)</strong>: não há interação entre Tratamento e Dose. O efeito de Tratamento na massa da parte aérea seca é o mesmo para todas as Doses.</li>
<li><strong>Hipótese alternativa 3 (Ha3)</strong>: existe uma interação entre Tratamento e Dose. O efeito de Tratamento na massa da parte aérea seca depende da dose aplicada.</li>
</ul>
<section id="análise-de-variância-anova" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-variância-anova">Análise de variância (ANOVA)</h3>
<p>Primeiramente foi realizada uma Two-Way ANOVA porque o conjunto de dados é um fatorial de tratamento e dose. Os dados foram primeiramente ajustados para o modelo de ANOVA usando a função <code>lm()</code>, a análise em si foi realizada utilizando a função <code>anova()</code>. A função <code>summary()</code> foi utilizada para visualização do resumo estatístico da ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mf <span class="ot">&lt;-</span> <span class="fu">lm</span>(MPAS <span class="sc">~</span> Trat<span class="sc">*</span><span class="fu">factor</span>(Dose),</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: MPAS
                  Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
Trat               3  462.83 154.276  3.8212 0.01393 *
factor(Dose)       3  125.63  41.877  1.0372 0.38218  
Trat:factor(Dose)  9  716.19  79.576  1.9710 0.05743 .
Residuals         64 2583.95  40.374                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MPAS ~ Trat * factor(Dose), data = controle)

Residuals:
   Min     1Q Median     3Q    Max 
-11.94  -3.22  -0.08   3.75  11.22 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              1.412e+01  2.842e+00   4.969 5.31e-06 ***
TratB                    8.445e-15  4.019e+00   0.000   1.0000    
TratC                   -5.123e-16  4.019e+00   0.000   1.0000    
TratD                    6.091e-15  4.019e+00   0.000   1.0000    
factor(Dose)1000         1.660e+00  4.019e+00   0.413   0.6809    
factor(Dose)10000       -4.620e+00  4.019e+00  -1.150   0.2546    
factor(Dose)1e+05       -1.460e+00  4.019e+00  -0.363   0.7176    
TratB:factor(Dose)1000  -2.800e+00  5.683e+00  -0.493   0.6239    
TratC:factor(Dose)1000  -5.500e+00  5.683e+00  -0.968   0.3368    
TratD:factor(Dose)1000   8.640e+00  5.683e+00   1.520   0.1334    
TratB:factor(Dose)10000  6.220e+00  5.683e+00   1.094   0.2779    
TratC:factor(Dose)10000  1.024e+01  5.683e+00   1.802   0.0763 .  
TratD:factor(Dose)10000  1.242e+01  5.683e+00   2.185   0.0325 *  
TratB:factor(Dose)1e+05  5.820e+00  5.683e+00   1.024   0.3097    
TratC:factor(Dose)1e+05  7.780e+00  5.683e+00   1.369   0.1758    
TratD:factor(Dose)1e+05  5.720e+00  5.683e+00   1.006   0.3180    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.354 on 64 degrees of freedom
Multiple R-squared:  0.3355,    Adjusted R-squared:  0.1798 
F-statistic: 2.154 on 15 and 64 DF,  p-value: 0.01772</code></pre>
</div>
</div>
<p>Baseado na tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) em relação aos tratamentos. Sendo assim, rejeita-se a hipótese nula <strong>H01</strong>. No entanto, o valor de “p” foi maior que o nível de significância (0,05) para a análise de dose e para a interação entre tratamento e dose. Dessa forma as hipóteses nulas <strong>H02</strong> e <strong>H03</strong> não são rejeitadas.</p>
<p>Como há pelo menos uma diferença entre os níveis do tratamento, devemos refazer a análise de variância levando em consideração somente esse fator.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mf1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MPAS <span class="sc">~</span> Trat,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: MPAS
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
Trat       3  462.8 154.276  3.4226 0.02136 *
Residuals 76 3425.8  45.076                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MPAS ~ Trat, data = controle)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.910  -4.290   0.840   5.531  13.985 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   13.015      1.501   8.669 5.74e-13 ***
TratB          2.310      2.123   1.088  0.28002    
TratC          3.130      2.123   1.474  0.14454    
TratD          6.695      2.123   3.153  0.00231 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.714 on 76 degrees of freedom
Multiple R-squared:  0.119, Adjusted R-squared:  0.08425 
F-statistic: 3.423 on 3 and 76 DF,  p-value: 0.02136</code></pre>
</div>
</div>
<p>Baseado na nova tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) e a hipótese nula deve ser rejeitada. Conclui-se então que pelo menos um dos tratamentos apresenta uma média com diferença estatística significativa na massa da parte aérea seca em relação aos outros tratamentos.</p>
<section id="checagem-das-premissas" class="level4">
<h4 class="anchored" data-anchor-id="checagem-das-premissas">Checagem das premissas</h4>
<p>Para verificar as premissas de normalidade e homocedasticidade das variâncias foi utilizada a função <code>check_</code> do pacote <code>performance</code>. A confirmação visual das premissas foi feita por meio da função <code>simulateResiduals()</code> do pacote <code>DHARMa</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mf1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf1) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.245).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(mf1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.710).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf1)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Tanto a checagem pelas funções do <code>performance</code> quanto a análise visual pelo <code>DHARMa</code> indicaram que ambas as premissas foram atendidas.</p>
</section>
<section id="grupos-distintos-estatisticamente" class="level4">
<h4 class="anchored" data-anchor-id="grupos-distintos-estatisticamente">Grupos distintos estatisticamente</h4>
<p>Para verificar os tratamentos que são distintos estatisticamente, primeiramente foi calculado a média dos grupos pelo <code>emmeans()</code> e depois foi utilizada a função <code>cld</code> do pacote <code>multcomp</code>. E para visualizar de forma gráfica essa diferença foi utilizada a função <code>plot</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mf_mpas1 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf1, <span class="sc">~</span>Trat)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_mpas1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Trat emmean  SE df lower.CL upper.CL .group
 A      13.0 1.5 76     10.0     16.0  1    
 B      15.3 1.5 76     12.3     18.3  12   
 C      16.1 1.5 76     13.2     19.1  12   
 D      19.7 1.5 76     16.7     22.7   2   

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cld</span>(mf_mpas1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por essa análise houve a formação de dois grupos (1 e 2). Sendo o número 1 atribuído ao tratamento A, representando o tratamento com menor média da massa aérea seca. Já o número 2 foi atribuído ao tratamento D, representando o tratamento com maior média da massa aérea seca. Sendo assim, os tratamentos A e D são estatisticamente distintos. Os tratamentos B e C foram atribuidos como 12 e são estatisticamente semelhantes tanto em relação ao tratamento A quanto ao tratamento D.</p>
</section>
</section>
</section>
<section id="variável-massa-da-raiz-fresca-mrf" class="level2">
<h2 class="anchored" data-anchor-id="variável-massa-da-raiz-fresca-mrf">Variável massa da raiz fresca (MRF)</h2>
<ul>
<li><strong>Hipótese nula 1 (H01)</strong>: não há diferença na média da massa da raiz fresca entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese alternativa 1 (Ha1)</strong>: há pelo menos uma diferença na média da massa da raiz fresca entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese nula 2 (H02)</strong>: não há diferença na média da massa da raiz fresca entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese alternativa 2 (Ha2)</strong>: há pelo menos uma diferença na média da massa da raiz fresca entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese nula 3 (H03)</strong>: não há interação entre Tratamento e Dose. O efeito de Tratamento na massa da raiz fresca é o mesmo para todas as Doses.</li>
<li><strong>Hipótese alternativa 3 (Ha3)</strong>: existe uma interação entre Tratamento e Dose. O efeito de Tratamento na massa da raiz fresca depende da dose aplicada.</li>
</ul>
<section id="análise-de-variância-anova-1" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-variância-anova-1">Análise de variância (ANOVA)</h3>
<p>Os passos para a análise de variância foram seguidos de forma semlhante ao realizado para a variável MPAS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mf2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MRF <span class="sc">~</span> Trat<span class="sc">*</span><span class="fu">factor</span>(Dose),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: MRF
                  Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
Trat               3  2600.7  866.91  3.4914 0.02058 *
factor(Dose)       3  2602.5  867.51  3.4938 0.02052 *
Trat:factor(Dose)  9  2823.2  313.69  1.2634 0.27416  
Residuals         64 15891.2  248.30                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MRF ~ Trat * factor(Dose), data = controle)

Residuals:
   Min     1Q Median     3Q    Max 
-33.08  -8.85   0.75  12.04  32.32 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              5.188e+01  7.047e+00   7.362  4.3e-10 ***
TratB                    8.106e-14  9.966e+00   0.000   1.0000    
TratC                    5.741e-14  9.966e+00   0.000   1.0000    
TratD                    6.521e-14  9.966e+00   0.000   1.0000    
factor(Dose)1000        -1.940e+00  9.966e+00  -0.195   0.8463    
factor(Dose)10000       -3.000e+00  9.966e+00  -0.301   0.7644    
factor(Dose)1e+05        1.018e+01  9.966e+00   1.021   0.3109    
TratB:factor(Dose)1000   3.360e+00  1.409e+01   0.238   0.8123    
TratC:factor(Dose)1000   1.126e+01  1.409e+01   0.799   0.4273    
TratD:factor(Dose)1000   1.826e+01  1.409e+01   1.296   0.1998    
TratB:factor(Dose)10000  2.180e+00  1.409e+01   0.155   0.8776    
TratC:factor(Dose)10000  1.498e+01  1.409e+01   1.063   0.2918    
TratD:factor(Dose)10000  3.456e+01  1.409e+01   2.452   0.0169 *  
TratB:factor(Dose)1e+05  3.920e+00  1.409e+01   0.278   0.7818    
TratC:factor(Dose)1e+05  1.502e+01  1.409e+01   1.066   0.2906    
TratD:factor(Dose)1e+05  3.180e+00  1.409e+01   0.226   0.8222    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15.76 on 64 degrees of freedom
Multiple R-squared:  0.3356,    Adjusted R-squared:  0.1799 
F-statistic: 2.155 on 15 and 64 DF,  p-value: 0.01768</code></pre>
</div>
</div>
<p>Baseado na tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) em relação aos tratamentos e as doses analisados de forma individual. No entanto, o valor de “p” foi maior que o nível de significância (0,05) para a interação entre tratamento e dose. Assim, devemos refazer a análise de variância levando em consideração somente os tratamentos distintos e, depois, somente as doses.</p>
</section>
<section id="anova-em-relação-aos-tratamentos" class="level3">
<h3 class="anchored" data-anchor-id="anova-em-relação-aos-tratamentos">ANOVA em relação aos tratamentos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mf21 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MRF <span class="sc">~</span> Trat,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf21)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: MRF
          Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
Trat       3  2600.7  866.91  3.0908 0.03199 *
Residuals 76 21316.9  280.49                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf21)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MRF ~ Trat, data = controle)

Residuals:
    Min      1Q  Median      3Q     Max 
-48.390  -8.114   1.777  10.624  42.745 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   53.190      3.745  14.203  &lt; 2e-16 ***
TratB          2.365      5.296   0.447  0.65647    
TratC         10.315      5.296   1.948  0.05515 .  
TratD         14.000      5.296   2.643  0.00996 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.75 on 76 degrees of freedom
Multiple R-squared:  0.1087,    Adjusted R-squared:  0.07356 
F-statistic: 3.091 on 3 and 76 DF,  p-value: 0.03199</code></pre>
</div>
</div>
<p>Baseado na nova tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) e a hipótese nula deve ser rejeitada. Conclui-se então que pelo menos um dos tratamentos apresenta diferença estatística significativa na média da massa da raiz fresca em relação aos outros tratamentos.</p>
<section id="checagem-das-premissas-1" class="level4">
<h4 class="anchored" data-anchor-id="checagem-das-premissas-1">Checagem das premissas</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf21)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf21) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p = 0.005).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(mf21)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.674).</code></pre>
</div>
</div>
<p>A análise visual pelo DHRAMa indicou que não havia problemas, no entanto, pela função <code>check_normality()</code> não houve normalidade dos resíduos. Assim, devemos transformar os dados.</p>
</section>
<section id="transformação-de-box-cox" class="level4">
<h4 class="anchored" data-anchor-id="transformação-de-box-cox">Transformação de Box-Cox</h4>
<p>Uma opção de transformação do conjunto de dados é por meio de box-cox. Nesse caso é encontrado um valor de lambda, que é o valor de X quando Y é máximo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">boxcox</span>(<span class="fu">lm</span>(controle<span class="sc">$</span>MRF<span class="fl">+0.1</span> <span class="sc">~</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> b<span class="sc">$</span>x[<span class="fu">which.max</span>(b<span class="sc">$</span>y)]</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.272727</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>controle<span class="sc">$</span>MRF21 <span class="ot">&lt;-</span> (controle<span class="sc">$</span>MRF <span class="sc">^</span> lambda <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">/</span> lambda</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>controle<span class="sc">$</span>MRF21</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 171.24977 111.07428  32.09340 135.01936 158.97082 169.34808 114.55813
 [8] 103.89092  34.10960 157.09921 165.24339 145.66361  74.91074  92.33766
[15]  78.92511 152.75060 130.81048 140.16793 196.37269 129.61318 171.24977
[22] 111.07428  32.09340 135.01936 158.97082 136.83181  92.61596  97.93723
[29] 170.29836 121.00387 123.66221  46.71144 175.06666 113.39430 132.61080
[36] 146.89096 269.13851 106.75199 171.24977 124.25461 171.24977 111.07428
[43]  32.09340 135.01936 158.97082 107.90103 196.69948 141.68998 173.15597
[50] 118.94482 158.34642 107.03900 192.13504 158.65856 162.10063 280.01866
[57] 186.94675 208.20933 161.16033 155.23233 171.24977 111.07428  32.09340
[64] 135.01936 158.97082 179.22175 158.65856 208.87123 131.11017 167.76681
[71] 298.11557 235.02717 205.89622 183.71956 173.47411 138.04296 203.91796
[78] 181.14647  99.06549 179.86284</code></pre>
</div>
</div>
</section>
<section id="anova-com-os-dados-transformados" class="level4">
<h4 class="anchored" data-anchor-id="anova-com-os-dados-transformados">Anova com os dados transformados</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>mf2.boxcox <span class="ot">&lt;-</span> <span class="fu">lm</span>(MRF21 <span class="sc">~</span> Trat,</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf2.boxcox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: MRF21
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
Trat       3  24272  8090.7  3.2532 0.02625 *
Residuals 76 189014  2487.0                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf2.boxcox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MRF21 ~ Trat, data = controle)

Residuals:
     Min       1Q   Median       3Q      Max 
-135.522  -26.210    3.406   31.433  137.297 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  124.710     11.151  11.183  &lt; 2e-16 ***
TratB          7.131     15.770   0.452  0.65243    
TratC         31.122     15.770   1.973  0.05208 .  
TratD         42.905     15.770   2.721  0.00807 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 49.87 on 76 degrees of freedom
Multiple R-squared:  0.1138,    Adjusted R-squared:  0.07882 
F-statistic: 3.253 on 3 and 76 DF,  p-value: 0.02625</code></pre>
</div>
</div>
<p>Foi observado um resultado similar à ANOVA realizada com os dados não transformados.</p>
</section>
<section id="checando-novamente-as-premissas-após-transformação" class="level4">
<h4 class="anchored" data-anchor-id="checando-novamente-as-premissas-após-transformação">Checando novamente as premissas após transformação</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf2.boxcox)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf2.boxcox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p = 0.015).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(mf2.boxcox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.459).</code></pre>
</div>
</div>
<p>A premissa da homocedasticidade da variância foi atendida.</p>
</section>
<section id="grupos-distintos-estatisticamente-1" class="level4">
<h4 class="anchored" data-anchor-id="grupos-distintos-estatisticamente-1">Grupos distintos estatisticamente</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>mf_mrf2<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf2.boxcox, <span class="sc">~</span>Trat)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_mrf2<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Trat emmean   SE df lower.CL upper.CL .group
 A       125 11.2 76      103      147  1    
 B       132 11.2 76      110      154  12   
 C       156 11.2 76      134      178  12   
 D       168 11.2 76      145      190   2   

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cld</span>(mf_mrf2<span class="fl">.1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por essa análise houve a formação de dois grupos (1 e 2). O número 1 foi atribuído ao tratamento A, representando o tratamento com a menor média da massa da raiz fresca. O número 2 foi atribuído ao tratamento D, representando o tratamento que possibilitou a maior média da massa da raiz fresca. Sendo assim, os tratamentos A e D são distintas estatisticamente para essa variável. Já os tratamentos B e C foram atribuidos como 12 e são estatisticamente semelhantes em relação aos demais.</p>
</section>
</section>
<section id="anova-em-relação-as-doses" class="level3">
<h3 class="anchored" data-anchor-id="anova-em-relação-as-doses">ANOVA em relação as doses</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>mf22 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MRF <span class="sc">~</span> <span class="fu">factor</span>(Dose),</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf22)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: MRF
             Df  Sum Sq Mean Sq F value Pr(&gt;F)  
factor(Dose)  3  2602.5  867.51  3.0931 0.0319 *
Residuals    76 21315.2  280.46                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf22)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MRF ~ factor(Dose), data = controle)

Residuals:
    Min      1Q  Median      3Q     Max 
-38.460  -9.483   2.250  11.178  44.690 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         51.880      3.745  13.854  &lt; 2e-16 ***
factor(Dose)1000     6.280      5.296   1.186  0.23938    
factor(Dose)10000    9.930      5.296   1.875  0.06463 .  
factor(Dose)1e+05   15.710      5.296   2.966  0.00402 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 16.75 on 76 degrees of freedom
Multiple R-squared:  0.1088,    Adjusted R-squared:  0.07363 
F-statistic: 3.093 on 3 and 76 DF,  p-value: 0.0319</code></pre>
</div>
</div>
<p>Baseado na nova tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) e a hipótese nula deve ser rejeitada. Conclui-se então que pelo menos uma das doses apresenta diferença estatística significativa na média da massa da raiz fresca em relação as outras doses.</p>
</section>
<section id="checagem-das-premissas-2" class="level3">
<h3 class="anchored" data-anchor-id="checagem-das-premissas-2">Checagem das premissas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf22)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf22) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.181).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(mf22)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.538).</code></pre>
</div>
</div>
<p>Ambas as premissas foram atendidas.</p>
<section id="grupos-distintos-estatisticamente-2" class="level4">
<h4 class="anchored" data-anchor-id="grupos-distintos-estatisticamente-2">Grupos distintos estatisticamente</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>mf_mrf2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf22, <span class="sc">~</span>Dose)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_mrf2<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Dose emmean   SE df lower.CL upper.CL .group
 0e+00   51.9 3.74 76     44.4     59.3  1    
 1e+03   58.2 3.74 76     50.7     65.6  12   
 1e+04   61.8 3.74 76     54.4     69.3  12   
 1e+05   67.6 3.74 76     60.1     75.0   2   

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cld</span>(mf_mrf2<span class="fl">.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por essa análise houve a formação de dois grupos (1 e 2). O número 1 foi atribuído a dose 0, representando a dose com menor média da massa da raiz fresca. O número 2 foi atribuído a dose 100.000, representando a dose que possibilitou a maior média da massa da raiz fresca. Sendo assim, as doses 0 e 100.000 são distintas estatisticamente para essa variável. As doses 1.000 e 10.000 foram atribuidos como 12 e são estatisticamente semelhantes em relação a dose 0 e a dose 100.000.</p>
</section>
</section>
</section>
<section id="variável-número-de-ovos-por-planta" class="level2">
<h2 class="anchored" data-anchor-id="variável-número-de-ovos-por-planta">Variável número de ovos por planta</h2>
<ul>
<li><strong>Hipótese nula 1 (H01)</strong>: não há diferença na média do número de ovos por planta entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese alternativa 1 (Ha1)</strong>: há pelo menos uma diferença na média do número de ovos por planta entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese nula 2 (H02)</strong>: não há diferença na média do número de ovos por planta entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese alternativa 2 (Ha2)</strong>: há pelo menos uma diferença na média do número de ovos por planta entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese nula 3 (H03)</strong>: não há interação entre Tratamento e Dose. O efeito de Tratamento no número de ovos por planta é o mesmo para todas as Doses.</li>
<li><strong>Hipótese alternativa 3 (Ha3)</strong>: existe uma interação entre Tratamento e Dose. O efeito de Tratamento no número de ovos por planta depende da dose aplicada.</li>
</ul>
<section id="análise-de-variância-anova-2" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-variância-anova-2">Análise de variância (ANOVA)</h3>
<p>Os passos para a análise de variância foram seguidos de forma semelhante aos realizados anteriormente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>mf3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ovos <span class="sc">~</span> Trat<span class="sc">*</span><span class="fu">factor</span>(Dose),</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: ovos
                  Df     Sum Sq    Mean Sq F value  Pr(&gt;F)  
Trat               3 5.1808e+09 1726936427  0.8407 0.47659  
factor(Dose)       3 2.5283e+10 8427647441  4.1027 0.01001 *
Trat:factor(Dose)  9 1.8756e+10 2084031988  1.0145 0.43813  
Residuals         64 1.3147e+11 2054169986                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ovos ~ Trat * factor(Dose), data = controle)

Residuals:
   Min     1Q Median     3Q    Max 
-87340 -30104    425  20750 126910 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              7.825e+04  2.027e+04   3.861 0.000266 ***
TratB                    5.179e-11  2.866e+04   0.000 1.000000    
TratC                   -3.606e-11  2.866e+04   0.000 1.000000    
TratD                   -5.319e-11  2.866e+04   0.000 1.000000    
factor(Dose)1000        -1.655e+04  2.866e+04  -0.577 0.565719    
factor(Dose)10000        5.150e+03  2.866e+04   0.180 0.857985    
factor(Dose)1e+05       -2.009e+04  2.866e+04  -0.701 0.486030    
TratB:factor(Dose)1000  -5.255e+04  4.054e+04  -1.296 0.199523    
TratC:factor(Dose)1000   1.010e+04  4.054e+04   0.249 0.804044    
TratD:factor(Dose)1000  -1.670e+04  4.054e+04  -0.412 0.681747    
TratB:factor(Dose)10000  1.320e+04  4.054e+04   0.326 0.745774    
TratC:factor(Dose)10000  1.743e+04  4.054e+04   0.430 0.668607    
TratD:factor(Dose)10000 -8.600e+03  4.054e+04  -0.212 0.832667    
TratB:factor(Dose)1e+05  5.793e+04  4.054e+04   1.429 0.157892    
TratC:factor(Dose)1e+05  5.094e+04  4.054e+04   1.256 0.213508    
TratD:factor(Dose)1e+05  2.537e+04  4.054e+04   0.626 0.533670    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 45320 on 64 degrees of freedom
Multiple R-squared:  0.2724,    Adjusted R-squared:  0.1019 
F-statistic: 1.597 on 15 and 64 DF,  p-value: 0.0996</code></pre>
</div>
</div>
<p>Baseado na tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) somente em relação às doses analisados de forma individual. Assim, rejeitamos a hipótese nula <strong>H02</strong> e não rejeitamos as demais hipóteses nulas. Dessa forma, devemos refazer a análise de variância levando em consideração somente as doses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>mf31 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ovos <span class="sc">~</span> <span class="fu">factor</span>(Dose),</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf31)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: ovos
             Df     Sum Sq    Mean Sq F value   Pr(&gt;F)   
factor(Dose)  3 2.5283e+10 8427647441  4.1215 0.009179 **
Residuals    76 1.5540e+11 2044789162                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf31)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ovos ~ factor(Dose), data = controle)

Residuals:
   Min     1Q Median     3Q    Max 
-90149 -34832     87  22388 151278 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          78250      10111   7.739 3.48e-11 ***
factor(Dose)1000    -31338      14300  -2.191   0.0315 *  
factor(Dose)10000    10658      14300   0.745   0.4584    
factor(Dose)1e+05    13472      14300   0.942   0.3491    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 45220 on 76 degrees of freedom
Multiple R-squared:  0.1399,    Adjusted R-squared:  0.106 
F-statistic: 4.122 on 3 and 76 DF,  p-value: 0.009179</code></pre>
</div>
</div>
<p>Baseado na nova tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) e a hipótese nula deve ser rejeitada. Conclui-se então que pelo menos uma das doses proporciona uma média no número de ovos por planta com diferença estatística significativa em relação as outras doses.</p>
<section id="checagem-das-premissas-3" class="level4">
<h4 class="anchored" data-anchor-id="checagem-das-premissas-3">Checagem das premissas</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf31)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf31) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.050).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(mf31)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.056).</code></pre>
</div>
</div>
<p>Ambas as premissas foram atendidas.</p>
</section>
<section id="grupos-distintos-estatisticamente-3" class="level4">
<h4 class="anchored" data-anchor-id="grupos-distintos-estatisticamente-3">Grupos distintos estatisticamente</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>mf_ovos3 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf31, <span class="sc">~</span>Dose)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_ovos3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Dose emmean    SE df lower.CL upper.CL .group
 1e+03  46913 10111 76    26774    67051  1    
 0e+00  78250 10111 76    58112    98389  12   
 1e+04  88908 10111 76    68770   109047   2   
 1e+05  91722 10111 76    71584   111861   2   

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cld</span>(mf_ovos3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por essa análise houve a formação de dois grupos (1 e 2). O número 1 foi atribuído a dose 1.000, representando a dose com menor média no número de ovos por planta. Já o número 2 foi atribuído as doses 10.000 e 100.000, sendo, então, as doses que propiciaram as maiores médias no número de ovos por planta. A dose 0 foi atribuida como 12, sendo estatisticamente semelhante as demais doses. Em resumo, não houve, estatisticamente, uma redução no número de ovos pelas doses das actinobactérias em relação a testemunha.</p>
</section>
</section>
</section>
<section id="variável-número-de-ovos-por-grama-de-raiz-fresca" class="level2">
<h2 class="anchored" data-anchor-id="variável-número-de-ovos-por-grama-de-raiz-fresca">Variável número de ovos por grama de raiz fresca</h2>
<ul>
<li><strong>Hipótese nula 1 (H01)</strong>: não há diferença na média do número de ovos por grama de raiz fresca entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese alternativa 1 (Ha1)</strong>: há pelo menos uma diferença na média do número de ovos por grama de raiz fresca entre os diferentes níveis de Tratamento.</li>
<li><strong>Hipótese nula 2 (H02)</strong>: não há diferença na média do número de ovos por grama de raiz fresca entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese alternativa 2 (Ha2)</strong>: há pelo menos uma diferença na média do número de ovos por grama de raiz fresca entre os diferentes níveis de Dose.</li>
<li><strong>Hipótese nula 3 (H03)</strong>: não há interação entre Tratamento e Dose. O efeito de Tratamento no número de ovos por grama de raiz fresca é o mesmo para todas as Doses.</li>
<li><strong>Hipótese alternativa 3 (Ha3)</strong>: existe uma interação entre Tratamento e Dose. O efeito de Tratamento no número de ovos por grama de raiz fresca depende da dose aplicada.</li>
</ul>
<section id="análise-de-variância-anova-3" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-variância-anova-3">Análise de variância (ANOVA)</h3>
<p>Os passos para a análise de variância foram seguidos de forma semelhante aos realizados anteriormente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>mf4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ovosg <span class="sc">~</span> Trat<span class="sc">*</span><span class="fu">factor</span>(Dose),</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: ovosg
                  Df   Sum Sq Mean Sq F value   Pr(&gt;F)   
Trat               3  1208226  402742  1.0877 0.360766   
factor(Dose)       3  6771820 2257273  6.0963 0.001028 **
Trat:factor(Dose)  9  6925511  769501  2.0782 0.044586 * 
Residuals         64 23697362  370271                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ovosg ~ Trat * factor(Dose), data = controle)

Residuals:
     Min       1Q   Median       3Q      Max 
-1202.77  -392.44     6.94   260.04  1508.62 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              1.468e+03  2.721e+02   5.393 1.07e-06 ***
TratB                   -3.518e-14  3.848e+02   0.000   1.0000    
TratC                   -1.131e-12  3.848e+02   0.000   1.0000    
TratD                   -1.419e-12  3.848e+02   0.000   1.0000    
factor(Dose)1000        -3.170e+02  3.848e+02  -0.824   0.4132    
factor(Dose)10000        1.651e+02  3.848e+02   0.429   0.6694    
factor(Dose)1e+05       -5.025e+02  3.848e+02  -1.306   0.1964    
TratB:factor(Dose)1000  -9.772e+02  5.443e+02  -1.795   0.0773 .  
TratC:factor(Dose)1000   2.897e+01  5.443e+02   0.053   0.9577    
TratD:factor(Dose)1000  -4.787e+02  5.443e+02  -0.880   0.3824    
TratB:factor(Dose)10000  4.100e+02  5.443e+02   0.753   0.4541    
TratC:factor(Dose)10000 -1.950e+01  5.443e+02  -0.036   0.9715    
TratD:factor(Dose)10000 -7.769e+02  5.443e+02  -1.427   0.1583    
TratB:factor(Dose)1e+05  6.491e+02  5.443e+02   1.193   0.2374    
TratC:factor(Dose)1e+05  4.153e+02  5.443e+02   0.763   0.4482    
TratD:factor(Dose)1e+05  3.506e+02  5.443e+02   0.644   0.5218    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 608.5 on 64 degrees of freedom
Multiple R-squared:  0.3861,    Adjusted R-squared:  0.2422 
F-statistic: 2.684 on 15 and 64 DF,  p-value: 0.003183</code></pre>
</div>
</div>
<p>Baseado na tabela de ANOVA, interpreta-se que o valor de “p” foi menor que o nível de significância (0,05) para a interação tratamento e dose e para o fator dose analisado individualmente. Sendo assim, rejeitamos as hipóteses nulas <strong>H02</strong> e <strong>H03</strong> e não rejeitamos a hipótese nula <strong>H01</strong>. A análise de variância fatorial pode, então, ser prosseguida.</p>
<section id="checando-as-premissas" class="level4">
<h4 class="anchored" data-anchor-id="checando-as-premissas">Checando as premissas</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf4)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.144).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(mf4) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Heteroscedasticity (non-constant error variance) detected (p &lt; .001).</code></pre>
</div>
</div>
<p>A premissa de normalidade dos dados foi atendida, no entanto as varianças não são homogêneas. Dessa forma, devemos transformar os dados.</p>
</section>
<section id="transformação-por-box-cox" class="level4">
<h4 class="anchored" data-anchor-id="transformação-por-box-cox">Transformação por Box-Cox</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> <span class="fu">boxcox</span>(<span class="fu">lm</span>(controle<span class="sc">$</span>ovosg<span class="fl">+0.1</span> <span class="sc">~</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>lambda2 <span class="ot">&lt;-</span> b2<span class="sc">$</span>x[<span class="fu">which.max</span>(b2<span class="sc">$</span>y)]</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>lambda2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6262626</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>controle<span class="sc">$</span>ovosg2 <span class="ot">&lt;-</span> (controle<span class="sc">$</span>ovosg <span class="sc">^</span> lambda2 <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">/</span> lambda2</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>controle<span class="sc">$</span>ovosg2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 170.33689 118.88560 146.38862 168.52370 152.45822 190.09820 137.30970
 [8]  99.23391 110.55957 101.38804 156.37812 220.67884  91.78136 103.28525
[15] 213.88081 166.54185  11.31234 121.74162  55.55632 170.85845 170.33689
[22] 118.88560 146.38862 168.52370 152.45822  39.24553  42.35897  42.73560
[29]  38.37365  30.22118 258.43490 248.03633 159.33759 106.69871 134.05353
[36] 182.55218 211.30812  86.37198 165.36517 144.80374 170.33689 118.88560
[43] 146.38862 168.52370 152.45822 172.21167 129.83580 106.72584 147.10459
[50]  97.77101 122.96513 171.62059 104.09197 216.51332 176.61513 156.59968
[57] 144.38360 176.15996 145.36809 102.64011 170.33689 118.88560 146.38862
[64] 168.52370 152.45822 112.19443  95.67674  72.58054 108.07759  69.30303
[71] 139.18090 135.33315  70.54905  73.32064 109.51726 229.84247 151.09387
[78] 102.66252 120.86746  75.49023</code></pre>
</div>
</div>
</section>
<section id="anova-fatorial-com-os-dados-transformados" class="level4">
<h4 class="anchored" data-anchor-id="anova-fatorial-com-os-dados-transformados">ANOVA fatorial com os dados transformados</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>mf4<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(ovosg2 <span class="sc">~</span> Trat<span class="sc">*</span><span class="fu">factor</span>(Dose),</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> controle)</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf4<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: ovosg2
                  Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Trat               3   6466  2155.3  1.2665 0.2933933    
factor(Dose)       3  38760 12919.9  7.5920 0.0002023 ***
Trat:factor(Dose)  9  44105  4900.6  2.8797 0.0064239 ** 
Residuals         64 108914  1701.8                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mf4<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ovosg2 ~ Trat * factor(Dose), data = controle)

Residuals:
   Min     1Q Median     3Q    Max 
-93.89 -26.87   1.14  18.45  93.85 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              1.513e+02  1.845e+01   8.202 1.42e-11 ***
TratB                    1.519e-13  2.609e+01   0.000   1.0000    
TratC                    1.332e-13  2.609e+01   0.000   1.0000    
TratD                    1.267e-13  2.609e+01   0.000   1.0000    
factor(Dose)1000        -2.360e+01  2.609e+01  -0.905   0.3691    
factor(Dose)10000        5.882e+00  2.609e+01   0.225   0.8223    
factor(Dose)1e+05       -4.612e+01  2.609e+01  -1.768   0.0819 .  
TratB:factor(Dose)1000  -8.913e+01  3.690e+01  -2.416   0.0186 *  
TratC:factor(Dose)1000   3.012e+00  3.690e+01   0.082   0.9352    
TratD:factor(Dose)1000  -3.615e+01  3.690e+01  -0.980   0.3309    
TratB:factor(Dose)10000  2.411e+01  3.690e+01   0.653   0.5158    
TratC:factor(Dose)10000  1.160e+00  3.690e+01   0.031   0.9750    
TratD:factor(Dose)10000 -5.162e+01  3.690e+01  -1.399   0.1666    
TratB:factor(Dose)1e+05  5.288e+01  3.690e+01   1.433   0.1567    
TratC:factor(Dose)1e+05  3.983e+01  3.690e+01   1.079   0.2844    
TratD:factor(Dose)1e+05  3.079e+01  3.690e+01   0.834   0.4071    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 41.25 on 64 degrees of freedom
Multiple R-squared:  0.4506,    Adjusted R-squared:  0.3218 
F-statistic: 3.499 on 15 and 64 DF,  p-value: 0.0002285</code></pre>
</div>
</div>
<p>Os resultados obtidos foram similares à ANOVA dos dados não transformados.</p>
</section>
<section id="checando-novamente-as-premissas-após-transformação-1" class="level4">
<h4 class="anchored" data-anchor-id="checando-novamente-as-premissas-após-transformação-1">Checando novamente as premissas após transformação</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf4<span class="fl">.1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf4<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.411).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(mf4<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.077).</code></pre>
</div>
</div>
<p>Ambas as premissas foram atendidas.</p>
</section>
<section id="grupos-distintos-estatisticamente-agrupados-em-função-da-dose" class="level4">
<h4 class="anchored" data-anchor-id="grupos-distintos-estatisticamente-agrupados-em-função-da-dose">Grupos distintos estatisticamente agrupados em função da Dose</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>mf_ovosg <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf4<span class="fl">.1</span>, <span class="sc">~</span> Trat<span class="sc">|</span>Dose)</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_ovosg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dose = 0e+00:
 Trat emmean   SE df lower.CL upper.CL .group
 A     151.3 18.4 64   114.46    188.2  1    
 D     151.3 18.4 64   114.46    188.2  1    
 B     151.3 18.4 64   114.46    188.2  1    
 C     151.3 18.4 64   114.46    188.2  1    

Dose = 1e+03:
 Trat emmean   SE df lower.CL upper.CL .group
 B      38.6 18.4 64     1.73     75.4  1    
 D      91.6 18.4 64    54.71    128.4  12   
 A     127.7 18.4 64    90.86    164.6   2   
 C     130.7 18.4 64    93.87    167.6   2   

Dose = 1e+04:
 Trat emmean   SE df lower.CL upper.CL .group
 D     105.6 18.4 64    68.72    142.4  1    
 A     157.2 18.4 64   120.35    194.1  12   
 C     158.4 18.4 64   121.51    195.2  12   
 B     181.3 18.4 64   144.46    218.2   2   

Dose = 1e+05:
 Trat emmean   SE df lower.CL upper.CL .group
 A     105.2 18.4 64    68.35    142.1  1    
 D     136.0 18.4 64    99.14    172.8  1    
 C     145.0 18.4 64   108.17    181.9  1    
 B     158.1 18.4 64   121.22    194.9  1    

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cld</span>(mf_ovosg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Houve diferença estatistica entre os tratamentos nas doses de 1.000 e 10.000. Em ambas as doses houve a formação de dois grupos distintos (1 e 2).</p>
<p>Na menor dose, o tratamento B foi atribuído ao número 1 e apresentou a menor média no número de ovos por grama de raiz. Os tratamentos A e C foram representados pelo número 2 e propiciaram, então, as maiores médias no número de ovos por grama de raiz. O tratamento D foi atribuído como 12 e, assim, não apresenta diferença estatística para os demais tratamentos nessa dose.</p>
<p>Já na dose 10.000, o tratamento D foi atribuído ao número 1 e apresentou a menor média no número de ovos por grama de raiz. O número 2 foi atribuído ao tratamento B, representando, então, a maior média no número de ovos por grama de raiz. E os tratamentos A e C foram representados como 12 e, assim, não apresentam diferença estatística para os demais tratamentos nessa dose.</p>
</section>
<section id="grupos-distintos-estatisticamente-agrupados-em-função-dos-tratamentos" class="level4">
<h4 class="anchored" data-anchor-id="grupos-distintos-estatisticamente-agrupados-em-função-dos-tratamentos">Grupos distintos estatisticamente agrupados em função dos Tratamentos</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>mf_ovosg2 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf4<span class="fl">.1</span>, <span class="sc">~</span>Dose<span class="sc">|</span>Trat)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_ovosg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Trat = A:
  Dose emmean   SE df lower.CL upper.CL .group
 1e+05  105.2 18.4 64    68.35    142.1  1    
 1e+03  127.7 18.4 64    90.86    164.6  1    
 0e+00  151.3 18.4 64   114.46    188.2  1    
 1e+04  157.2 18.4 64   120.35    194.1  1    

Trat = B:
  Dose emmean   SE df lower.CL upper.CL .group
 1e+03   38.6 18.4 64     1.73     75.4  1    
 0e+00  151.3 18.4 64   114.46    188.2   2   
 1e+05  158.1 18.4 64   121.22    194.9   2   
 1e+04  181.3 18.4 64   144.46    218.2   2   

Trat = C:
  Dose emmean   SE df lower.CL upper.CL .group
 1e+03  130.7 18.4 64    93.87    167.6  1    
 1e+05  145.0 18.4 64   108.17    181.9  1    
 0e+00  151.3 18.4 64   114.46    188.2  1    
 1e+04  158.4 18.4 64   121.51    195.2  1    

Trat = D:
  Dose emmean   SE df lower.CL upper.CL .group
 1e+03   91.6 18.4 64    54.71    128.4  1    
 1e+04  105.6 18.4 64    68.72    142.4  1    
 1e+05  136.0 18.4 64    99.14    172.8  1    
 0e+00  151.3 18.4 64   114.46    188.2  1    

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cld</span>(mf_ovosg2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Houve diferença estatística entre as doses somente para o tratamento B com a formação de dois grupos distintos (1 e 2). A dose 1.000 foi atribuída ao número 1 e representa a menor média no número de ovos por grama de raiz. Já as demais doses foram representadas pelo número 2, apresentando uma média no número de ovos por grama de raiz superior a encontrada pela dose 1.000. Sendo assim, houve o controle do nematoide pelo número de ovos por grama de raiz somente no tratamento B na dose de 1.000.</p>
</section>
</section>
</section>
</section>
<section id="regressão" class="level1">
<h1>Regressão</h1>
<p>A regressão é uma técnica estatística utilizada para modelar e analisar a relação entre uma variável dependente (ou resposta) e uma ou mais variáveis independentes (ou preditoras). O objetivo principal da regressão é entender como a variável dependente varia quando as variáveis independentes mudam e usar essa compreensão para fazer previsões.</p>
<p>Com o conjunto de dados do experimento, foi analisado a relação entre a variável resposta do número de ovos por planta com os diferentes níveis de dose de actinobactérias.</p>
<p>Como ponto de partida, foi construído um gráfico pelo <code>ggplot()</code> usando em conjunto a função <code>geom_smooth(method = "lm")</code> para observar a linha de tendência da dispersão dos pontos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Dose, ovos))<span class="sc">+</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"gray"</span>)<span class="sc">+</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_boot"</span>, <span class="at">color =</span> <span class="st">"blue"</span>)<span class="sc">+</span></span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Com esse gráfico podemos observar que a distância entre os valores da Dose é de uma escala exponencial, o que dificulta a visualização e a compreensão do gráfico. Por esse motivo, o fator Dose foi transformado por log(x + 0.5), de forma a “encurtar” o espaço entre os dados e facilitar a sua análise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">log</span>(Dose<span class="fl">+0.5</span>), ovos))<span class="sc">+</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"gray"</span>)<span class="sc">+</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_boot"</span>, <span class="at">color =</span> <span class="st">"blue"</span>)<span class="sc">+</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observando o gráfico podemos perceber que o ajuste com o modelo linear não aparenta representar o nosso conjunto de dados. Ao retirarmos o ajuste, temos o seguinte gráfico:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">log</span>(Dose<span class="fl">+0.5</span>), ovos))<span class="sc">+</span></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"gray"</span>)<span class="sc">+</span></span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_boot"</span>, <span class="at">color =</span> <span class="st">"blue"</span>)<span class="sc">+</span></span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Para comparar tanto o modelo linear quanto o modelo quadrático, pode ser feito um gráfico que contenha os dois modelos juntos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">log</span>(Dose<span class="fl">+0.5</span>), ovos))<span class="sc">+</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"gray"</span>)<span class="sc">+</span></span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> <span class="st">"mean_cl_boot"</span>, <span class="at">color =</span> <span class="st">"blue"</span>)<span class="sc">+</span></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> y <span class="sc">~</span><span class="fu">poly</span>(x,<span class="dv">2</span>))<span class="sc">+</span></span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Pelo gráfico pode-se observar que, embora também não represente perfeitamente o conjunto de dados, o modelo quadrático é melhor que o modelo linear para explicar a relação entre a variável resposta do número de ovos por planta com a Dose.</p>
<p>A fim de comparar os dois modelos, pode ser utilizado a função <code>polynomial()</code> do pacote <code>AgroR</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(controle, <span class="fu">polynomial</span>(<span class="fu">log</span>(Dose<span class="fl">+0.5</span>), ovos, <span class="at">grau =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
----------------------------------------------------
Regression Models
----------------------------------------------------
             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 69621.096   9513.065 7.3184712 1.940508e-10
trat         1013.735   1167.482 0.8683087 3.878891e-01

----------------------------------------------------
Deviations from regression
----------------------------------------------------
          Df          SSq         MSQ         F     p-value
Linear     1   1729826968  1729826968 0.8459684 0.360605535
Deviation  2  23553115356 11776557678 5.7593017 0.004689236
Residual  76 155403976291  2044789162                      </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(controle, <span class="fu">polynomial</span>(<span class="fu">log</span>(Dose<span class="fl">+0.5</span>), ovos, <span class="at">grau =</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
----------------------------------------------------
Regression Models
----------------------------------------------------
              Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 71003.0278  9170.2382  7.742768 3.177367e-11
trat        -8476.6973  3709.5726 -2.285087 2.506088e-02
I(trat^2)     941.8122   350.8368  2.684474 8.891006e-03

----------------------------------------------------
Deviations from regression
----------------------------------------------------
          Df          SSq         MSQ         F     p-value
Linear     1   1729826968  1729826968 0.8459684 0.360605535
Quadratic  1  15315182702 15315182702 7.4898591 0.007721708
Deviation  1   8237932653  8237932653 4.0287443 0.048287173
Residual  76 155403976291  2044789162                      </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análise-de-correlação" class="level1">
<h1>Análise de Correlação</h1>
<p>Como foram obtidas três variáveis respostas a partir do experimento base, além da variável resposta de ovos/g, e estas variáveis foram analisadas separadamente, foi realizado uma análise para avaliar se essas variáveis estão correlacionadas, ou seja, se existe alguma associação entre elas. Por meio da análise de correlação, testou-se a seguinte hipótese:</p>
<ul>
<li><p>Hipótese nula (H0): não há correlação significativa entre as duas variáveis analisadas.</p></li>
<li><p>Hipótese alternativa (Ha): há uma correlação significativa entre as duas variáveis analisadas.</p></li>
</ul>
<section id="correlação-entre-ovos-e-massa-de-parte-aérea-seca-mpas" class="level2">
<h2 class="anchored" data-anchor-id="correlação-entre-ovos-e-massa-de-parte-aérea-seca-mpas">Correlação entre Ovos e Massa de Parte Aérea Seca (MPAS)</h2>
<p><strong>Visualização gráfica da correlação</strong>: O primeiro passo para analisar a correlação entre duas variáveis quantitativas deve ser a visualização do gráfico de dispersão, a fim de identificar se existe uma variabilidade gradual entre os conjuntos de dados, se essa variação é monotônica (predominantemente ascendente ou descendente) e se assume uma tendência proporcional (linear).</p>
<p>A visualização gráfica foi montada com um <code>ggplot()</code> usando as funções <code>geom_point()</code> e <code>geom_smooth()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(ovos, MPAS))<span class="sc">+</span></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Baseando apenas na análise visual do gráfico de dispersão, é possível inferir que existe uma correlação positiva entre as variáveis “Ovos” e “MPAS”, tendo em vista que a linha de tendência criada pelo <code>geom_smooth()</code> tem um perfil ascendente.</p>
<p><strong>Teste de Correlação</strong>: Para realizar o teste de correlação, usou-se a função <code>cor.test()</code>, que é parte do pacote base do R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(controle<span class="sc">$</span>ovos, controle<span class="sc">$</span>MPAS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  controle$ovos and controle$MPAS
t = 4.3922, df = 78, p-value = 3.49e-05
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2500414 0.6057460
sample estimates:
      cor 
0.4452945 </code></pre>
</div>
</div>
<p>O p-valor da análise da relação entre as variáveis foi menor do que o nível de significância (0,05), indicando que a hipótese nula deve ser rejeitada. Além disso, a análise de correlação para as variáveis “Ovos” e “MPAS” obteve um coeficiente de correlação de Pearson estimado de 0.44, demonstrando que existe uma correlação fraca positiva entre as duas variáveis, lembrando que para correlação positiva o coeficiente de correlação (r) varia de 0 a 1.</p>
</section>
<section id="correlação-entre-ovos-e-massa-de-raiz-fresca-mrf" class="level2">
<h2 class="anchored" data-anchor-id="correlação-entre-ovos-e-massa-de-raiz-fresca-mrf">Correlação entre Ovos e Massa de Raiz Fresca (MRF)</h2>
<p><strong>Visualização gráfica da correlação</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(ovos, MRF))<span class="sc">+</span></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Baseando apenas na análise visual do gráfico de dispersão, é possível inferir que existe uma correlação positiva entre as variáveis “Ovos” e “MRF”, tendo em vista que a linha de tendência criada pelo <code>geom_smooth()</code> tem um perfil ascendente.</p>
<p><strong>Teste de Correlação</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(controle<span class="sc">$</span>ovos, controle<span class="sc">$</span>MRF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  controle$ovos and controle$MRF
t = 5.0825, df = 78, p-value = 2.491e-06
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.3134107 0.6475340
sample estimates:
      cor 
0.4987807 </code></pre>
</div>
</div>
<p>O p-valor da análise da relação entre as variáveis foi menor do que o nível de significância (0,05), indicando que a hipótese nula deve ser rejeitada. Além disso, a análise de correlação para as variáveis “Ovos” e “MRF” obteve um coeficiente de correlação de Pearson estimado de 0.49, sendo maior que a correlação entre “Ovos” e “MPAS”, embora ainda seja considerado uma correlação fraca positiva entre as duas variáveis.</p>
</section>
<section id="correlação-entre-massa-de-parte-aérea-seca-mpas-e-massa-de-raiz-fresca-mrf" class="level2">
<h2 class="anchored" data-anchor-id="correlação-entre-massa-de-parte-aérea-seca-mpas-e-massa-de-raiz-fresca-mrf">Correlação entre Massa de Parte Aérea Seca (MPAS) e Massa de Raiz Fresca (MRF)</h2>
<p><strong>Visualização gráfica da correlação</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span> </span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(MPAS, MRF))<span class="sc">+</span></span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Diferente dos outros dois gráficos, a primeira diferença que é possível de observar é a menor dispersão entre os dados das duas variáveis, o que normalmente indica uma correlação mais forte. Isso também é perceptível pela barra de erros nesse gráfico, sendo mais afunilado se comparado aos outros dois anteriores. Novamente a linha de tendência criada pelo <code>geom_smooth()</code> tem um perfil ascendente.</p>
<p><strong>Teste de Correlação</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(controle<span class="sc">$</span>MPAS, controle<span class="sc">$</span>MRF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  controle$MPAS and controle$MRF
t = 9.4015, df = 78, p-value = 1.799e-14
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6062088 0.8176291
sample estimates:
      cor 
0.7288474 </code></pre>
</div>
</div>
<p>Novamente o p-valor da análise da relação entre as variáveis foi menor do que o nível de significância (0,05), indicando que a hipótese nula deve ser rejeitada. Nessa análise de correlação, podemos observar que as variáveis “MPAS” e “MRF” obtiveram um coeficiente de correlação de Pearson estimado de 0.72, bem maior que os coeficientes vistos na duas correlações anteriores, demonstrando que existe uma correlação positiva mais forte entre essas duas variáveis.</p>
<p>Essa correlação mais forte entre as variáveis “MPAS” e “MRF” era, na verdade, já esperado por nós, uma vez que biologicamente existe uma correlação forte entre a massa da raiz e a massa da parte aérea, ou seja, já é esperado que uma planta que possua maior biomassa de raiz tenha uma maior biomassa da parte aérea.</p>
</section>
<section id="correlação-entre-todas-as-variáveis" class="level2">
<h2 class="anchored" data-anchor-id="correlação-entre-todas-as-variáveis">Correlação entre todas as variáveis</h2>
<p>É possível visualizar a correlação entre todas as variáveis resposta através de um único gráfico a partir da função ´corgraph()<code>do pacote</code>AgroR`.</p>
<p>Para isso, é preciso primeiro filtrar apenas os dados das variáveis resposta. A esse conjunto de dados filtrado foi atribuído o nome <code>controle2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>controle2 <span class="ot">&lt;-</span> controle[, <span class="fu">c</span>(<span class="st">"ovos"</span>, <span class="st">"MPAS"</span>, <span class="st">"MRF"</span>)]</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corgraph</span>(controle2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Var2       cor            p
2 MPAS ovos 0.4452945 3.490166e-05
3  MRF ovos 0.4987807 2.490892e-06
6  MRF MPAS 0.7288474 1.799052e-14</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Projeto_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>